### ISSUE TITLE
Module03: Materials for dplyr lesson

### ISSUE THREAD

**Issue by tavareshugo** [tavareshugo/slcu_r_course#3]
List of things that we think should be covered in the `dplyr` lesson:

- `filter`
- `select`
- `mutate`
- Introduce pipes `%>%`
- "split-and-apply" summaries: `data %>% group_by %>% summarise`

**Comment by tavareshugo** [comment]
Perhaps it's also good if we relate this to the previous `ggplot` lesson

**Comment by scortijo** [comment]
A first draft of the module 03 is done. Please have a look and let me know if anything needs to be changed!
